;; Table indices include imports before local tables of either reference type.
(module $provider
  (type $value (func (result i32)))
  (table (export "table") 1 funcref)
  (func (export "call") (result i32)
    (call_indirect (type $value) (i32.const 0))))
(register "provider" $provider)

(module $consumer
  (type $value (func (result i32)))
  (import "provider" "table" (table $imported 1 funcref))
  (table $refs 1 3 externref)
  (table $funcs 2 funcref)
  (func $seven (result i32) (i32.const 7))
  (elem (table $funcs) (i32.const 0) func $seven)
  (func (export "sizes") (result i32 i32 i32)
    (table.size $imported) (table.size $refs) (table.size $funcs))
  (func (export "get") (param i32) (result externref)
    (table.get $refs (local.get 0)))
  (func (export "set") (param externref)
    (table.set $refs (i32.const 0) (local.get 0)))
  (func (export "grow") (param externref i32) (result i32)
    (table.grow $refs (local.get 0) (local.get 1)))
  (func (export "fill") (param externref)
    (table.fill $refs (i32.const 1) (local.get 0) (i32.const 2)))
  (func (export "copy")
    (table.copy $refs $refs (i32.const 0) (i32.const 1) (i32.const 2)))
  (func (export "call") (result i32)
    (call_indirect $funcs (type $value) (i32.const 0)))
  (func (export "share")
    (table.copy $imported $funcs (i32.const 0) (i32.const 0) (i32.const 1))))

(assert_return (invoke $consumer "sizes") (i32.const 1) (i32.const 1) (i32.const 2))
(assert_return (invoke $consumer "get" (i32.const 0)) (ref.null extern))
(assert_return (invoke $consumer "set" (ref.extern 11)))
(assert_return (invoke $consumer "grow" (ref.extern 22) (i32.const 2)) (i32.const 1))
(assert_return (invoke $consumer "get" (i32.const 0)) (ref.extern 11))
(assert_return (invoke $consumer "get" (i32.const 2)) (ref.extern 22))
(assert_return (invoke $consumer "fill" (ref.extern 33)))
(assert_return (invoke $consumer "copy"))
(assert_return (invoke $consumer "get" (i32.const 0)) (ref.extern 33))
(assert_return (invoke $consumer "sizes") (i32.const 1) (i32.const 3) (i32.const 2))
(assert_return (invoke $consumer "grow" (ref.null extern) (i32.const 1)) (i32.const -1))
(assert_trap (invoke $consumer "get" (i32.const 3)) "out of bounds table access")
(assert_return (invoke $consumer "call") (i32.const 7))
(assert_return (invoke $consumer "share"))
;; A local function copied into the imported table remains callable by its owner.
(assert_return (invoke $provider "call") (i32.const 7))

;; Table 1 is externref, even though local table array entry 1 is funcref.
(assert_invalid
  (module (import "provider" "table" (table 1 funcref))
    (table 1 externref) (table 1 funcref)
    (func (result funcref) (table.get 1 (i32.const 0))))
  "type mismatch")
(assert_invalid
  (module (import "provider" "table" (table 1 funcref))
    (table 1 externref) (table 1 funcref)
    (func (table.set 1 (i32.const 0) (ref.null func))))
  "type mismatch")
(assert_invalid
  (module (import "provider" "table" (table 1 funcref))
    (table 1 externref) (table 1 funcref)
    (func (result i32) (table.grow 1 (ref.null func) (i32.const 1))))
  "type mismatch")
(assert_invalid
  (module (import "provider" "table" (table 1 funcref))
    (table 1 externref) (table 1 funcref)
    (func (table.fill 1 (i32.const 0) (ref.null func) (i32.const 1))))
  "type mismatch")
(assert_invalid
  (module (import "provider" "table" (table 1 funcref))
    (table 1 externref) (table 1 funcref)
    (func (table.copy 0 1 (i32.const 0) (i32.const 0) (i32.const 1))))
  "type mismatch")
(assert_invalid
  (module (type $void (func))
    (import "provider" "table" (table 1 funcref))
    (table 1 externref) (table 1 funcref)
    (func (call_indirect 1 (type $void) (i32.const 0))))
  "type mismatch")
(assert_invalid
  (module (import "provider" "table" (table 1 funcref))
    (table 1 externref) (table 1 funcref)
    (func (result i32) (table.size 3)))
  "unknown table")
